apiVersion: v1
kind: ServiceAccount
metadata:
  name: artisan-runner
  namespace: ${OPENSHIFT_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-runs
  namespace: ${OPENSHIFT_NAMESPACE}
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: [
        "triggerbindings",
        "triggertemplates",
        "eventlisteners",
      ]
    verbs: [ "get", "list", "create", "update", "delete", "patch", "watch" ]

  - apiGroups: ["tekton.dev"]
    resources: [
        "tasks",
        "taskruns",
        "pipelines",
        "pipelineruns",
        "pipelineresources",
        "conditions",
        "runs"
    ]
    verbs: [ "get", "list", "create", "update", "delete", "patch", "watch" ]

  - apiGroups: ["*"] # all api groups
    resources: [
        "secrets",
        "routes",
        "pods"
    ]
    verbs: [ "get", "list", "create", "update", "delete", "patch", "watch" ]
    
  - apiGroups: ["*"] # all api groups
    resources: [
        "pods/log"
    ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-runs-rule
  namespace: ${OPENSHIFT_NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: artisan-runner
    namespace: ${OPENSHIFT_NAMESPACE}
    apiGroup: ""
roleRef:
  kind: Role
  name: manage-runs
  apiGroup: rbac.authorization.k8s.io
...