apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-ci-runs
  namespace: ci-namespace # create role in ci-namespace
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: [
        "triggerbindings",
        "triggertemplates",
        "eventlisteners",
      ]
    verbs: [ "get", "list", "create", "update", "delete", "patch", "watch" ]

  - apiGroups: ["tekton.dev"]
    resources: [
        "tasks",
        "taskruns",
        "pipelines",
        "pipelineruns",
        "pipelineresources",
        "conditions",
        "runs"
    ]
    verbs: [ "get", "list", "create", "update", "delete", "patch", "watch" ]

  - apiGroups: ["*"] # all api groups
    resources: [
        "secrets",
        "routes",
        "pods"
    ]
    verbs: [ "get", "list", "create", "update", "delete", "patch", "watch" ]
    
  - apiGroups: ["*"] # all api groups
    resources: [
        "pods/log"
    ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-ci-runs-rule
  namespace: ci-namespace   # create role-binding in ci namespace
subjects:
  - kind: ServiceAccount
    name: artisan-runner    # bind role to the srtisan-runner sa deployed in setup namespace
    namespace: default
    apiGroup: ""
roleRef:
  kind: Role
  name: manage-ci-runs
  apiGroup: rbac.authorization.k8s.io
---