---
functions:
  - name: publish
    description: publishes all runtimes
    run:
      - art run build-image art-java11
      - art run build-image art-rhctools
      - art run build-image art-kube
...