---
env:
  REPO_NAME: quay.io/artisan
  IMG_NAME: ansible_terraform
  ART_PACKAGE: artisan

functions:
  - name: build
    description: builds and push docker image
    run:
      - docker build -t=${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF} .
      - docker tag ${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF} ${REPO_NAME}/${IMG_NAME}:latest

  - name: push
    description: builds and push docker image
    run:
      - docker push ${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF}
      - docker push ${REPO_NAME}/${IMG_NAME}:latest

  - name: version
    description: prints the versions for the tools in this runtime
    runtime: ansible_terraform
    run:
      - terraform --version
      - ansible -v
...
