---
app_icon: quarkus

env:
  APP_NAME: app

input:
  var:
    - name: GIT_URI
      description: the URI of the project git repository
      required: true
      type: uri

    - name: SONAR_URI
      description: the URI of the SonarQube server to use for code quality reporting
      required: true
      type: uri

    - name: SONAR_PROJECT_KEY
      description: the unique key identifying the project in the SonarQube server
      required: true
      type: string

    - name: SONAR_SOURCES
      description: the path the sonar scanner should use to scan source code
      required: true
      type: path
      default: src/

    - name: SONAR_BINARIES
      description: the path the sonar scanner should use to scan binary files
      required: true
      type: path
      default: target/classes

    - name: IMG_PACKAGE_NAME
      description: the name:tag for the image builder package to be published (e.g. registry-host/app-group/img-name)
      required: true
      type: name

    - name: APP_PACKAGE_NAME
      description: the name:tag for the application package to be published (e.g. registry-host/app-group/app-name)
      required: true
      type: name

    - name: PROJECT_GROUP_ID
      description: the maven group id for the project
      required: true
      type: string

    - name: PROJECT_ARTIFACT_ID
      description: the maven artifact id for the application
      required: true
      type: string

    - name: PROJECT_ARTIFACT_VERSION
      description: the version of the application artifact
      required: true
      type: string
      default: "0.0.1"

  secret:
    - name: ART_REG_USER
      description: the artisan registry user
    - name: ART_REG_PWD
      description: the artisan registry password
    - name: SONAR_TOKEN
      description: the token to access the Sonar server

  key:
    - name: SIGNING_KEY
      description: the private PGP key required to digitally sign the application package
      private: true
      path: /

profiles:
  - name: app
    description: packages the java application uber jar file
    default: true
    type: content/java
    target: target/${PROJECT_ARTIFACT_ID}-${PROJECT_ARTIFACT_VERSION}-runner.jar
    run:
      - $(build-app)

  - name: image
    description: builds the image builder package
    runtime: buildah
    type: exe/image/builder
    target: _build/image

functions:
  - name: build-app
    description: compiles and tests the application
    run:
      - mvn package -DskipTests=true
      - mvn test

  - name: publish-app
    description: packages and publishes the application
    run:
      - art build -t=${APP_PACKAGE_NAME} -p app
      - art push ${APP_PACKAGE_NAME} -u=${ART_REG_USER}:${ART_REG_PWD}
    input:
      var:
        - APP_PACKAGE_NAME
      secret:
        - ART_REG_USER
        - ART_REG_PWD
      key:
        - SIGNING_KEY

  - name: init
    description: initialises the project and creates pipelines
    export: true
    runtime: java
    run:
      # creates the quarkus scaffold for the project
      - mvn io.quarkus:quarkus-maven-plugin:1.11.1.Final:create -DprojectGroupId=${PROJECT_GROUP_ID} -DprojectArtifactId=${PROJECT_ARTIFACT_ID} -DprojectVersion=${PROJECT_ARTIFACT_VERSION}
      # copy project files to the correct location
      - cp -r ${PROJECT_ARTIFACT_ID}/. .
      # remove old folder
      - rm -R ${PROJECT_ARTIFACT_ID}
      # copy the docker file to build the jvm version to the image builder package folder
      - cp src/main/docker/Dockerfile.jvm _build/image/Dockerfile
      # build the image builder package
      - art build -t ${IMG_PACKAGE_NAME} -p image
      # create a tekton pipeline resources file
      - art flow merge -b . --tkn _build/flows/s2p_bare.yaml
    input:
      var:
        - GIT_URI
        - PROJECT_GROUP_ID
        - PROJECT_ARTIFACT_ID
        - PROJECT_ARTIFACT_VERSION
        - SONAR_URI
        - SONAR_PROJECT_KEY
        - SONAR_SOURCES
        - SONAR_BINARIES
        - SONAR_TOKEN
        - APP_PACKAGE_NAME
        - IMG_PACKAGE_NAME
        - ART_REG_USER
        - ART_REG_PWD
        - SIGNING_KEY
...
