---
app_icon: quarkus

env:
  APP_NAME: app

input:
  var:
    - name: GIT_URI
      description: the URI of the project git repository
      required: true
      type: uri

    - name: SONAR_URI
      description: the URI of the SonarQube server to use for code quality reporting
      required: true
      type: uri

    - name: SONAR_PROJECT_KEY
      description: the unique key identifying the project in the SonarQube server
      required: true
      type: string

    - name: SONAR_SOURCES
      description: the path the sonar scanner should use to scan source code
      required: true
      type: path
      default: src/

    - name: SONAR_BINARIES
      description: the path the sonar scanner should use to scan binary files
      required: true
      type: path
      default: target/classes

    - name: APP_PACKAGE_NAME
      description: the name:tag for the application package to be published (e.g. registry-host/app-group/app-name)
      required: true
      type: name

    - name: PROJECT_GROUP_ID
      description: the maven group id for the project
      required: true
      type: string

    - name: PROJECT_ARTIFACT_ID
      description: the maven artifact id for the application
      required: true
      type: string

    - name: PROJECT_ARTIFACT_VERSION
      description: the version of the application artifact
      required: true
      type: string
      default: 0.0.1

    - name: BC_LAUNCHER_PACKAGE_NAME
      description: the name:tag for the build configuration launcher package used to trigger the image build in OpenShift
      required: true
      type: name

  secret:
    - name: ART_REG_USER
      description: the artisan registry user
    - name: ART_REG_PWD
      description: the artisan registry password
    - name: SONAR_TOKEN
      description: the token to access the Sonar server

  key:
    - name: SIGNING_KEY
      description: the private PGP key required to digitally sign the application package
      private: true
      path: /

profiles:
  - name: app
    description: packages the java application uber jar file
    default: true
    type: content/java
    run:
      # copy the docker file to build the jvm version to the artefact(target) package folder
      - cp src/main/docker/Dockerfile.jvm target/target
      # copy the build.yaml file to build the jvm version to the artefact(target) package folder
      - cp _build/image/build.yaml target/target
    target: target/target

  - name: image
    description: builds the image builder package
    runtime: buildah
    type: exe/image/builder
    target: _build/image

functions:
  - name: build-app
    description: compiles and tests the application
    run:
      - mvn package -DskipTests=true
      - mvn test
      - mkdir target/target
      - cp target/${PROJECT_ARTIFACT_ID}-${PROJECT_ARTIFACT_VERSION}-runner.jar target/target
      - cp -r target/lib/. target/target/lib
    input:
      var:
        - PROJECT_ARTIFACT_ID
        - PROJECT_ARTIFACT_VERSION

  - name: publish-app
    description: packages and publishes the application
    run:
      - art build -t=${APP_PACKAGE_NAME} -p app
      - art push ${APP_PACKAGE_NAME} -u=${ART_REG_USER}:${ART_REG_PWD}
    input:
      var:
        - APP_PACKAGE_NAME
      secret:
        - ART_REG_USER
        - ART_REG_PWD
      key:
        # needs this binding to mount the key in the container
        - SIGNING_KEY

  - name: init
    description: initialises the project and creates pipelines
    export: true
    runtime: java
    run:
      # creates the quarkus scaffold for the project
      # the plugin version below might need upgrading if the current one is not available anymore
      - mvn io.quarkus:quarkus-maven-plugin:1.11.2.Final:create -DprojectGroupId=${PROJECT_GROUP_ID} -DprojectArtifactId=${PROJECT_ARTIFACT_ID} -DprojectVersion=${PROJECT_ARTIFACT_VERSION}
      # copy project files to the correct location
      - cp -r ${PROJECT_ARTIFACT_ID}/. .
      # remove old folder
      - rm -R ${PROJECT_ARTIFACT_ID}
    input:
      var:
        - GIT_URI
        - PROJECT_GROUP_ID
        - PROJECT_ARTIFACT_ID
        - PROJECT_ARTIFACT_VERSION
        - SONAR_URI
        - SONAR_PROJECT_KEY
        - SONAR_SOURCES
        - SONAR_BINARIES
        - SONAR_TOKEN
        - APP_PACKAGE_NAME
        - ART_REG_USER
        - ART_REG_PWD
        - SIGNING_KEY

  - name: git-init
    description: initialises the git repository
    run:
      - git init
      - git add .
      - git commit -m first_commit
      - git remote add origin ${GIT_URI}
      - git push -u origin master

  - name: app-pipeline
    description: create a tekton pipeline in openshift to build the application
    run:
      # create a tekton pipeline resources file
      - art flow merge -b . --tkn _build/flows/s2p_bare.yaml
      # apply pipeline to OpenShift
      - oc apply -f _build/flows/s2p_tkn.yaml

  - name: img-pipeline
    description: create a tekton pipeline in openshift to build the docker image
    run:
      - rm -f _build/image/Dockerfile
      # merge the name of the BC_LAUNCHER_PACKAGE_NAME into the p2i template
      - art merge _build/flows/p2i_bare.yaml.tem
      # create a tekton pipeline resources file
      - art flow merge -b . --tkn _build/flows/p2i_bare.yaml
      # apply the resource file to OpenShift
      - oc apply -f _build/flows/p2i_tkn.yaml
    input:
      var:
        - APP_PACKAGE_NAME
        - ART_REG_USER
        - ART_REG_PWD
        - BC_LAUNCHER_PACKAGE_NAME
...
