---
input:
  var:
    - name: APP_PACKAGE_NAME
      description: the name:tag for the application package to be published
      required: true
      type: name

  secret:
    - name: ART_REG_USER
      description: the artisan registry user
      aggregate: true
    - name: ART_REG_PWD
      description: the artisan registry password
      aggregate: true

  key:
    - name: SIGNING_KEY
      description: the private PGP key required to digitally sign the application package
      private: true

profiles:
  - name: app
    description: packages the java uber jar file
    default: true
    type: content/java
    labels:
      author: <<Author Here>>
      application: <<Name of the App Here>>
      description: <<Description for the App Here>>
      license: <<License Terms Here>>
    application: <<App Name Here>>
    target: target/<<App Name Here>>-1.0-SNAPSHOT-runner.jar

functions:
  - name: build-app
    description: compiles and tests the application
    run:
      - mvn package -DskipTests=true
      - mvn test

  - name: publish-app
    description: packages and publishes the application
    run:
      - art build -t=${PACKAGE_NAME}
      - art push ${PACKAGE_NAME} -u=${ART_REG_USER}:${ART_REG_PWD}
    input:
      var:
        - PACKAGE_NAME
      secret:
        - ART_REG_USER
        - ART_REG_PWD
      key:
        - SIGNING_KEY
...
