---
input:
  # variable definition section
  var:
    - name: USER_TO_GREET
      description: the name of the user to greet
      required: true
      default: Gatblau
      type: string

functions:
  - name: greet-user
    run:
      - echo Hello ${USER_TO_GREET}!
    input:
      # variable binding section
      var:
        - USER_TO_GREET
...