apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: artie-runner-template
  xpaas: 1.0.0
message: Artisan Runner based application has been created in your project.
metadata:
  annotations:
    description: Artisan Runner - Implemented in golang.
    iconClass: icon-go-gopher
    openshift.io/display-name: Artisan Runner
    openshift.io/provider-display-name: Artisan Project
    tags: artie, artie runner, artisan
    template.openshift.io/documentation-url: https://github.com/gatblau/onix/tree/develop/artie
    template.openshift.io/long-description: Artisan Runner
    template.openshift.io/support-url: https://access.redhat.com
    version: 1.0.0
  labels:
  name: artie-runner-template
  selfLink: /apis/template.openshift.io/v1/namespaces/openshift/templates/artie-runner-template
objects:
- apiVersion: v1
  kind: "ImageStream"
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ${ARTIE_RUNNER_IMAGE}
      generation: 1
      importPolicy: 
        scheduled: true
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
      app.kubernetes.io/part-of: Artisan
      app.openshift.io/runtime: go-gopher
      app.kubernetes.io/name: openshift-artie-runner
      app.kubernetes.io/instance: openshift-artie-runner
      app.kubernetes.io/component: integration
    annotations:
      app.openshift.io/connects-to: artisan-runner
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        serviceAccountName: artisan-runner
        serviceAccount: artisan-runner
        containers:
        - env:
          - name: OX_HTTP_UNAME
            valueFrom:
              secretKeyRef:
                key: uname
                name: ${APPLICATION_NAME}-creds
          - name: OX_HTTP_PWD
            valueFrom:
              secretKeyRef:
                key: pwd
                name: ${APPLICATION_NAME}-creds
          image: ${APPLICATION_NAME}
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - curl -u ${OX_HTTP_UNAME}:${OX_HTTP_PWD} localhost:8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          resources: {}
        terminationGracePeriodSeconds: 30
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  id: ${APPLICATION_NAME}-https
  kind: Route
  metadata:
    annotations:
      description: Route for application's https service.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    port:
      targetPort: "8080"
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APPLICATION_NAME}-creds
  type: Opaque
  stringData:
    uname: "${OX_HTTP_UNAME}"
    pwd: "${OX_HTTP_PWD}"
parameters:
- description: The name for the application
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: artisan-runner
- description: Enter Artisan Runner User Name
  displayName: Artisan Runner User Name
  name: OX_HTTP_UNAME
  required: true
- description: Enter Artisan Runner Password
  displayName: Artisan Runner Password
  name: OX_HTTP_PWD
  required: true
- description: Repo URL for Artisan Runner Image
  displayName: Artisan Runner Image URL
  name: ARTIE_RUNNER_IMAGE
  value: quay.io/gatblau/artisan-runner
  required: true
