ERR_CANT_CREATE_REGISTRY_FOLDER = "स्थानीय रजिस्ट्री फ़ोल्डर '%s' नहीं बना सकता, उपयोगकर्ता घर: '%s'"
ERR_CANT_DOWNLOAD_LANG = "'%s' से भाषा शब्दकोश डाउनलोड नहीं कर सकते"
ERR_CANT_EXEC_FUNC_IN_PACKAGE = "पैकेज '%s' में '%s' फ़ंक्शन निष्पादित नहीं कर सकता"
ERR_CANT_LOAD_PRIV_KEY = "निजी कुंजी लोड नहीं कर सकते"
ERR_CANT_PUSH_PACKAGE = "धक्का नहीं कर सकते पैकेज"
ERR_CANT_READ_RESPONSE = "HTTP प्रतिसाद निकाय नहीं पढ़ सकते हैं"
ERR_CANT_SAVE_FILE = "फ़ाइल को सहेज नहीं सकते"
ERR_CANT_UPDATE_LANG_FILE = "भाषा फ़ाइल अपडेट नहीं की जा सकती"
ERR_INSUFFICIENT_ARGS = "अपर्याप्त तर्क"
ERR_INVALID_PACKAGE_NAME = "अमान्य पैकेज नाम"
ERR_TOO_MANY_ARGS = "बहुत ज़्यादा बहस"
INFO_NOTHING_TO_PUSH = "पुश करने के लिए कुछ भी नहीं\n"
INFO_PUSHED = "धकेल दिया: %s\n"
LBL_LS_HEADER = "भंडार\tटैग\tपैकेज पहचान\tबंडल का प्रकार\tबनाया था\tआकार"
