# --------------------------------------------------------------
# Artisan Dictionary for Hindi Language
# --------------------------------------------------------------

# त्रुटि संदेश
ERR_CANT_CREATE_REGISTRY_FOLDER = "स्थानीय रजिस्ट्री फ़ोल्डर '%s' नहीं बना सकता, उपयोगकर्ता घर: '%s'"
ERR_CANT_EXEC_FUNC_IN_PACKAGE   = "पैकेज '%s' में '%s' फ़ंक्शन निष्पादित नहीं कर सकता"
ERR_CANT_LOAD_PRIV_KEY          = "निजी कुंजी लोड नहीं कर सकते"
ERR_CANT_PUSH_PACKAGE           = "धक्का नहीं कर सकते पैकेज"
ERR_INVALID_PACKAGE_NAME        = "अमान्य पैकेज नाम"

# सूचना संदेश
INFO_PUSHED                     = "धकेल दिया: %s\n"
INFO_NOTHING_TO_PUSH            = "पुश करने के लिए कुछ भी नहीं\n"

# लेबल
LBL_LS_HEADER                   = "भंडार\tटैग\tपैकेज पहचान\tबंडल का प्रकार\tबनाया था\tआकार"