---
env:
  REPO_NAME: quay.io/artisan
  IMG_NAME: vmdiskfs
  VMDISKFS_PACKAGE: vmdiskfs

functions:
  - name: build-image
    description: builds and push docker image
    run:
      - art open ${VMDISKFS_PACKAGE} . -s
      - docker build --squash -t=${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF} .
      - docker tag ${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF} ${REPO_NAME}/${IMG_NAME}:latest
      - docker push ${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF}
      - docker push ${REPO_NAME}/${IMG_NAME}:latest
      - rm ./vmdiskfs

  - name: version
    description: prints the versions for the tools in this runtime
    runtime: vmdiskfs
    run:
      - qemu-img --version
      - vmdiskfs version
      - openssl version
...