---
profiles:
  - name: bc-launcher
    default: true
    runtime: quay.io/gatblau/art-rhctools
    target: bc-launcher

  - name: quarkus
    description: builds the quarkus utility package library
    type: lib/quarkus
    target: quarkus
...